In [1]:
import numpy as np
from numpy.core.fromnumeric import _all_dispatcher
import pandas as pd
import joblib
np.random.seed(2021)
import warnings
warnings.filterwarnings('ignore')

# df --> whole training set

In [2]:
df = pd.read_csv("train_modified.gz", compression='gzip', header='infer')
Y = df['click']
# discard some columns
# unused_cols = ["id", 'site_id', 'app_id']
# df.drop(unused_cols, axis=1, inplace=True)

In [3]:
df

click  hour  C1  banner_pos   site_id site_domain site_category  \
0            0     0   5           0  078d3465    dd641cc7      8fd0aea4   
1            0     0   5           0  078d3465    dd641cc7      8fd0aea4   
2            0     0   5           0  078d3465    dd641cc7      8fd0aea4   
3            0     0   5           0  078d3465    dd641cc7      8fd0aea4   
4            0     0   5           1  a2af7bee    cbee4b41      72722551   
...        ...   ...  ..         ...       ...         ...           ...   
2683782      0     1   5           1  c12ebe86    c1aa3c04      74073276   
2683783      0     1   5           1  c12ebe86    c1aa3c04      74073276   
2683784      1     1   5           0  5bb07e04    b256a9bc      f66779e6   
2683785      0     1   5           1  c12ebe86    c1aa3c04      74073276   
2683786      0     1   5           1  c12ebe86    c1aa3c04      74073276   

        device_id device_ip device_model  ...  C19  C20  C21  day_of_week  \
0        a99f214a  ddd2926e     44956a24  ...    3   -1   67            1   
1        a99f214a  96809ac8     711ee120  ...    3   85   67            1   
2        a99f214a  b3cf8def     8a4875bd  ...    3   85   67            1   
3        a99f214a  e8275b8f     6332421a  ...    3   85   67            1   
4        a99f214a  9644d0bf     779d90c2  ...    3   -1  145            1   
...           ...       ...          ...  ...  ...  ...  ...          ...   
2683782  a99f214a  8546df25     67fb3069  ...    7   -1  145            2   
2683783  a99f214a  98e4ada3     b314d7b9  ...  131   -1   49            2   
2683784  a99f214a   Unknown     76dc4769  ...  135   -1   11            2   
2683785  a99f214a  e5693fd8     7120e05e  ...    7   -1   11            2   
2683786  a99f214a  af4a9787     0b188ab3  ...    7   -1   11            2   

         device_ip_count  device_id_count  hour_count              user  \
0                   7647          2533255      140117  ddd2926e44956a24   
1                      7          2533255      140117  96809ac8711ee120   
2                      2          2533255      140117  b3cf8def8a4875bd   
3                      6          2533255      140117  e8275b8f6332421a   
4                     31          2533255      140117  9644d0bf779d90c2   
...                  ...              ...         ...               ...   
2683782              229          2533255      147294  8546df2567fb3069   
2683783               18          2533255      147294  98e4ada3b314d7b9   
2683784           378614          2533255      147294  dc38aa0776dc4769   
2683785                9          2533255      147294  e5693fd87120e05e   
2683786              593          2533255      147294  af4a97870b188ab3   

         hourly_user_count                                      click_history  
0                      4.0                                       first string  
1                      3.0                                       first string  
2                      2.0                                       first string  
3                      2.0                                       first string  
4                     15.0                                       first string  
...                    ...                                                ...  
2683782                5.0                                               1110  
2683783                4.0                                                010  
2683784                1.0                                       first string  
2683785                4.0                                            0000010  
2683786               27.0  0000010001000000001000100000000000010000000100...  

[2683787 rows x 27 columns]

### df_train --> our own training set

In [4]:
df_train = pd.read_csv("train_df.gz", compression='gzip', header='infer')
Y_train = df_train['click']
df_train

click  hour  C1  banner_pos   site_id site_domain site_category  \
0            0     0   5           0  078d3465    dd641cc7      8fd0aea4   
1            0     0   5           0  078d3465    dd641cc7      8fd0aea4   
2            0     0   5           0  078d3465    dd641cc7      8fd0aea4   
3            0     0   5           0  078d3465    dd641cc7      8fd0aea4   
4            0     0   5           1  a2af7bee    cbee4b41      72722551   
...        ...   ...  ..         ...       ...         ...           ...   
2051079      1    15   5           0  f63cbdb9    16365701      74073276   
2051080      1    15   5           1  8480f5b7    3eda54e5      74073276   
2051081      1    15   5           0  078d3465    dd641cc7      8fd0aea4   
2051082      0    15   5           1  a831e579    437312ac      74073276   
2051083      0    15   5           0  08bbff54    22b04553      74073276   

        device_id device_ip device_model  ...  C19  C20  C21  day_of_week  \
0        a99f214a  ddd2926e     44956a24  ...    3   -1   67            1   
1        a99f214a  96809ac8     711ee120  ...    3   85   67            1   
2        a99f214a  b3cf8def     8a4875bd  ...    3   85   67            1   
3        a99f214a  e8275b8f     6332421a  ...    3   85   67            1   
4        a99f214a  9644d0bf     779d90c2  ...    3   -1  145            1   
...           ...       ...          ...  ...  ...  ...  ...          ...   
2051079  a99f214a  57cd4006     711ee120  ...    3   -1  209            1   
2051080  a99f214a   Unknown     84ebbcd4  ...    7   -1   11            1   
2051081  a99f214a  139b68fd     76dc4769  ...    3   85  209            1   
2051082  a99f214a  57bf6be0     d787e91b  ...    3   -1   31            1   
2051083  a99f214a   Unknown     597f7364  ...    3   -1   31            1   

         device_ip_count  device_id_count  hour_count              user  \
0                   5539          1936483       93115  ddd2926e44956a24   
1                      7          1936483       93115  96809ac8711ee120   
2                      2          1936483       93115  b3cf8def8a4875bd   
3                      5          1936483       93115  e8275b8f6332421a   
4                     31          1936483       93115  9644d0bf779d90c2   
...                  ...              ...         ...               ...   
2051079             5334          1936483      113179  57cd4006711ee120   
2051080           296165          1936483      113179  bc33a2d584ebbcd4   
2051081                2          1936483      113179  139b68fd76dc4769   
2051082                4          1936483      113179  57bf6be0d787e91b   
2051083           296165          1936483      113179  39a762f3597f7364   

         hourly_user_count                                      click_history  
0                        3                                       first string  
1                        3                                       first string  
2                        2                                       first string  
3                        2                                       first string  
4                       15                                       first string  
...                    ...                                                ...  
2051079                 21  0000101010100101000101000100101010110010000001...  
2051080                  1                                       first string  
2051081                  2                                                  1  
2051082                  1                                       first string  
2051083                  1                                       first string  

[2051084 rows x 27 columns]

In [5]:
Y_train[:1000]

0      0
1      0
2      0
3      0
4      0
      ..
995    0
996    0
997    0
998    0
999    0
Name: click, Length: 1000, dtype: int64

### Optimal catboost

In [15]:
from sklearn.model_selection import train_test_split

df_cat = df_train.copy()
unused_cols = ['site_id', 'click']
df_cat.drop(unused_cols, axis=1, inplace=True)
cut_off = int(len(df_cat) * 0.7)
X_train_cat = df_cat.iloc[:cut_off, :]
X_test_cat = df_cat.iloc[cut_off:, :]
y_train_cat = Y_train[:cut_off]
y_test_cat = Y_train[cut_off:]

In [ ]:
from catboost import CatBoostClassifier
from sklearn.metrics import log_loss
from skopt import BayesSearchCV
from skopt.space import Real, Categorical, Integer
from sklearn.metrics import make_scorer

categorical_f = ['C1', 'banner_pos','site_domain','site_category','device_id','device_ip','device_model',
                 'device_type','device_conn_type', 'C14','C15','C16','C17','C18', 'C19','C20','C21',
                 'day_of_week', 'user', 'click_history']

cat1 = CatBoostClassifier(iterations=20,learning_rate=0.1,depth=7,loss_function='Logloss', 
                          cat_features=categorical_f,verbose=False)

param = {
    'iterations': Integer(10, 1000),
    'depth': Integer(1, 8),
    'learning_rate': Real(0.01, 1.0, 'log-uniform'),
    'random_strength': Real(1e-9, 10, 'log-uniform'),
    'bagging_temperature': Real(0.0, 1.0),
    'border_count': Integer(1, 255),
    'l2_leaf_reg': Integer(2, 30),
    'scale_pos_weight':Real(0.01, 1.0, 'uniform')
}

LogLoss = make_scorer(log_loss, greater_is_better=False, needs_proba=True)

# log-uniform: understand as search over p = exp(x) by varying x
opt_c = BayesSearchCV(
    cat1,
    param,
    scoring = LogLoss,
    n_iter=64,
    cv=5,
    random_state=42
)

# executes bayesian optimization
opt_c.fit(X_train_cat, y_train_cat)

In [ ]:
opt_c.best_score_

In [ ]:
opt_c.best_params_

### optimal xgboost

In [6]:
df_xgb = df_train.copy()

def convert_obj_to_int(self):
    
    object_list_columns = self.columns
    object_list_dtypes = self.dtypes
    new_col_suffix = '_int'
    for index in range(0,len(object_list_columns)):
        if object_list_dtypes[index] == object :
            self[object_list_columns[index]+new_col_suffix] = self[object_list_columns[index]].map( lambda  x: hash(x))
            self.drop([object_list_columns[index]],inplace=True,axis=1)
    return self

df_xgb = convert_obj_to_int(df_xgb)
cut_off = int(len(df_xgb) * 0.7)
X_train_xgb = df_xgb.iloc[:cut_off, :]
X_test_xgb = df_xgb.iloc[cut_off:, :]
y_train_xgb = Y_train[:cut_off]
y_test_xgb = Y_train[cut_off:]

In [11]:
from xgboost import XGBClassifier
from sklearn.metrics import log_loss
from skopt import BayesSearchCV
from skopt.space import Real, Categorical, Integer
from sklearn.metrics import make_scorer

xgb1 = XGBClassifier(max_depth=3,learning_rate=0.1, alpha=0, colsample_bytree = 0.5,
                     subsample=0.1,n_estimators=100,gamma=0)

param = {
    'iterations': Integer(10, 400),
    'max_depth': Integer(3, 8, 'uniform'),
    'learning_rate': Real(0.01, 1.0, 'log-uniform'),
    'alpha': Real(0, 1.0, 'uniform'),
    'colsample_bytree' : Real(0.5,1.0, 'uniform'),
    'subsample': Real(0.1, 1.0, 'uniform'),
    'n_estimnators': Integer(100, 1000, 'uniform'),
    'gamma': Real(0, 1.0, 'uniform')
}

LogLoss = make_scorer(log_loss, greater_is_better=False, needs_proba=True)

# log-uniform: understand as search over p = exp(x) by varying x
opt_x = BayesSearchCV(
    xgb1,
    param,
    scoring = LogLoss,
    n_iter=40,
    cv=5,
    random_state=42
)

# executes bayesian optimization
opt_x.fit(X_train_xgb, y_train_xgb)

[22:22:59] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:541: 
Parameters: { iterations, n_estimnators } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.


[22:23:00] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[22:23:24] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:541: 
Parameters: { iterations, n_estimnators } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an i

[22:28:08] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[22:28:36] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:541: 
Parameters: { iterations, n_estimnators } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.


[22:28:36] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[22:29:05] WARNING: /Users/travis/build/dmlc/xgboost/src/lear

[22:33:23] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[22:33:41] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:541: 
Parameters: { iterations, n_estimnators } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.


[22:33:42] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[22:34:00] WARNING: /Users/travis/build/dmlc/xgboost/src/lear

[22:38:23] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[22:38:42] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:541: 
Parameters: { iterations, n_estimnators } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.


[22:38:43] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[22:39:03] WARNING: /Users/travis/build/dmlc/xgboost/src/lear

[22:43:30] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[22:43:43] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:541: 
Parameters: { iterations, n_estimnators } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.


[22:43:44] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[22:43:57] WARNING: /Users/travis/build/dmlc/xgboost/src/lear

[22:48:03] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[22:48:36] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:541: 
Parameters: { iterations, n_estimnators } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.


[22:48:37] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[22:49:09] WARNING: /Users/travis/build/dmlc/xgboost/src/lear

[22:53:10] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[22:53:32] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:541: 
Parameters: { iterations, n_estimnators } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.


[22:53:32] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[22:53:53] WARNING: /Users/travis/build/dmlc/xgboost/src/lear

[22:56:52] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[22:57:05] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:541: 
Parameters: { iterations, n_estimnators } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.


[22:57:06] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[22:57:18] WARNING: /Users/travis/build/dmlc/xgboost/src/lear

[23:01:31] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[23:01:48] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:541: 
Parameters: { iterations, n_estimnators } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.


[23:01:49] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[23:02:07] WARNING: /Users/travis/build/dmlc/xgboost/src/lear

[23:07:13] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[23:08:10] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:541: 
Parameters: { iterations, n_estimnators } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.


[23:08:11] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[23:09:07] WARNING: /Users/travis/build/dmlc/xgboost/src/lear

[23:15:32] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[23:16:09] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:541: 
Parameters: { iterations, n_estimnators } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.


[23:16:10] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[23:16:28] WARNING: /Users/travis/build/dmlc/xgboost/src/lear

[23:19:38] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[23:19:55] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:541: 
Parameters: { iterations, n_estimnators } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.


[23:19:55] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[23:20:19] WARNING: /Users/travis/build/dmlc/xgboost/src/lear

[23:24:34] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[23:24:57] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:541: 
Parameters: { iterations, n_estimnators } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.


[23:24:58] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[23:25:20] WARNING: /Users/travis/build/dmlc/xgboost/src/lear

[23:30:02] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[23:30:29] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:541: 
Parameters: { iterations, n_estimnators } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.


[23:30:30] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[23:30:59] WARNING: /Users/travis/build/dmlc/xgboost/src/lear

[23:34:04] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[23:34:19] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:541: 
Parameters: { iterations, n_estimnators } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.


[23:34:19] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[23:34:32] WARNING: /Users/travis/build/dmlc/xgboost/src/lear

[23:38:34] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[23:38:57] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:541: 
Parameters: { iterations, n_estimnators } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.


[23:38:58] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[23:39:14] WARNING: /Users/travis/build/dmlc/xgboost/src/lear

BayesSearchCV(cv=5,
              estimator=XGBClassifier(alpha=0, base_score=None, booster=None,
                                      colsample_bylevel=None,
                                      colsample_bynode=None,
                                      colsample_bytree=0.5, gamma=0,
                                      gpu_id=None, importance_type='gain',
                                      interaction_constraints=None,
                                      learning_rate=0.1, max_delta_step=None,
                                      max_depth=3, min_child_weight=None,
                                      missing=nan, monotone_constraints=None,
                                      n_estimators=100, n_job...
                             'iterations': Integer(low=10, high=400, prior='uniform', transform='identity'),
                             'learning_rate': Real(low=0.01, high=1.0, prior='log-uniform', transform='identity'),
                             'max_depth': Intege

In [13]:
opt_x.best_score_

-1.5349627176835216e-06

In [14]:
opt_x.best_params_

OrderedDict([('alpha', 0.0),
             ('colsample_bytree', 1.0),
             ('gamma', 0.0),
             ('iterations', 400),
             ('learning_rate', 0.27950642975302614),
             ('max_depth', 5),
             ('n_estimnators', 100),
             ('subsample', 1.0)])

### optimal lightgbm

In [ ]:
df_lgb = df_train.copy()

def convert_obj_to_int(self):
    
    object_list_columns = self.columns
    object_list_dtypes = self.dtypes
    new_col_suffix = '_int'
    for index in range(0,len(object_list_columns)):
        if object_list_dtypes[index] == object :
            self[object_list_columns[index]+new_col_suffix] = self[object_list_columns[index]].map( lambda  x: hash(x))
            self.drop([object_list_columns[index]],inplace=True,axis=1)
    return self

df_lgb = convert_obj_to_int(df_lgb)
cut_off = int(len(df_lgb) * 0.7)
X_train_lgb = df_lgb.iloc[:cut_off, :]
X_test_lgb = df_lgb.iloc[cut_off:, :]
y_train_lgb = Y_train[:cut_off]
y_test_lgb = Y_train[cut_off:]

In [ ]:
from skopt import BayesSearchCV
from skopt.space import Real, Categorical, Integer
from sklearn.metrics import make_scorer, auc, log_loss, roc_auc_score

import lightgbm as lgb

# categorical_f = [ca for ca in X_train.columns if X_train[ca].dtype == 'object']
lgb_model = lgb.LGBMClassifier(boosting_type='gbdt', objective='binary', metric='binary_logloss', bagging_freq=5)

param = {
    'max_depth': Integer(3, 7),
    'learning_rate': Real(0.01, 1.0, 'log-uniform'),
    'feature_fraction': Real(0.2, 0.9, 'uniform'),
    'bagging_fraction': Real(0.2, 0.9, 'log-uniform'),
    'max_bin': Integer(20, 255, 'uniform'),
    'n_estimators': Integer(100, 1000, 'uniform'),
    'num_leaves': Integer(24, 80, 'uniform'),
    'min_sum_hessian_in_leaf':Integer(0,100, 'uniform'),
}

# log-uniform: understand as search over p = exp(x) by varying x
opt_l = BayesSearchCV(
    lgb_model,
    param,
    scoring = LogLoss,
    n_iter=32,
    cv=5,
    random_state=42,
    verbose=5
)

# executes bayesian optimization
opt_l.fit(X_train_lgb, y_train_lgb)

## K-fold

In [15]:
df_opt = df_train.copy()
unused_cols = ['site_id', 'click']
df_opt.drop(unused_cols, axis=1, inplace=True)

In [16]:
best_p_c = {
    'iterations': 400,
    'depth': 4,
    'learning_rate': 1.0,
    'random_strength': 10,
    'bagging_temperature': 1.0,
    'border_count': 255,
    'l2_leaf_reg': 30,
    'scale_pos_weight':0.86438264586532
}

best_p_x = {
    'alpha':0.0,
    'colsample_bytree':1.0,
    'gamma':0.0,
    'iterations':400,
    'learning_rate':0.27950642975302614,
    'max_depth':5,
    'n_estimnators':100,
    'subsample':1.0
}

best_p_l = {
    'boosting_type':'gbdt', 
    'objective': 'binary', 
    'metric':'binary_logloss', 
    'bagging_freq': 5, 
    'max_depth': 7,
    'learning_rate': 0.11304216699488043,
    'feature_fraction': 0.5066204305086464,
    'bagging_fraction': 0.6657456066570288,
    'max_bin': 188,
    'n_estimators': 482,
    'num_leaves': 60,
    'min_sum_hessian_in_leaf':72
}

In [19]:
from sklearn.model_selection import KFold

# preds = np.zeros(test.shape[0])
kf = KFold(n_splits=10,random_state=42,shuffle=True)
logloss_c=[]
logloss_x=[]  # list contains rmse for each fold
logloss_l=[]
proba_cat_li=[]
proba_xgb_li=[]
proba_lgb_li=[]
y_li = []
n=0
df_opt_hash = convert_obj_to_int(df_opt)

categorical_f = ['C1', 'banner_pos','site_domain','site_category','device_id','device_ip','device_model',
                 'device_type','device_conn_type', 'C14','C15','C16','C17','C18', 'C19','C20','C21',
                 'day_of_week', 'user', 'click_history']

#     preds+=xgb.predict(test[columns])/kf.n_splits
for train_idx, test_idx in kf.split(df_opt,Y_train):
    X_tr,X_val=df_opt.iloc[train_idx],df_opt.iloc[test_idx]
    y_tr,y_val=Y_train.iloc[train_idx],Y_train.iloc[test_idx]
    
    X_tr_hash,X_val_hash=df_opt_hash.iloc[train_idx],df_opt_hash.iloc[test_idx]
    
    cat = CatBoostClassifier(**best_p_l,od_type='Iter', loss_function='Logloss', cat_features=categorical_f)
    cat.fit(X_tr,y_tr,eval_set=[(X_val,y_val)],early_stopping_rounds=100,verbose=Falsen)
    proba_cat = cat.predict_proba(X_val.values)[:, 1]
    proba_cat_li.append(proba_cat)
    logloss_c.append(log_loss(y_val, proba_cat))
    print(n+1,logloss_c[n])
    
    xgb = XGBClassifier(**best_p_x, loss_function='Logloss')
    xgb.fit(X_tr_hash,y_tr,eval_set=[(X_val_hash,y_val)],early_stopping_rounds=100,verbose=False)
    proba_xgb = xgb.predict_proba(X_val_hash.values)[:, 1]
    proba_xgb_li.append(proba_xgb)
    logloss_x.append(log_loss(y_val, proba_xgb))
    print(n+1,logloss_x[n])
    
    lgb = lgb.LGBMClassifier(best_p_l, loss_function='Logloss')
    lgb.fit(X_tr_hash,y_tr,eval_set=[(X_val_hash,y_val)],early_stopping_rounds=100, verbose=False)
    proba_lgb = lgb.predict_proba(X_val_hash.values)[:, 1]
    proba_lgb_li.append(proba_lgb)
    logloss_l.append(log_loss(y_val, proba_lgb))
    print(n+1,logloss_l[n])
    n+1
    
    y_li.append(y_val)

[23:58:04] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:541: 
Parameters: { iterations, loss_function, n_estimnators } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.


[23:58:06] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
1 0.42108933834823564
[23:59:46] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:541: 
Parameters: { iterations, loss_function, n_estimnators } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used bu

In [20]:
logloss

[0.42108933834823564,
 0.4245085451378775,
 0.4227249105200798,
 0.4242787822622415,
 0.42484490639534866,
 0.4231111782452581,
 0.42411352536754104,
 0.4226289177814561,
 0.42166378761430084,
 0.42496272631344667]

In [40]:
weights_range = [0.001, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5,
       0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95, 0.999]

In [ ]:
%%timeit
# bag of models in Catboost, xgboost, lightgbm
model_num = 3
cv_num = 10
#create placeholder for results table
output_wts_li = []
for i in range(cv_num):
    output_wts = np.zeros((len(X_val),model_num+1))
    output_wts_li.append(output_wts)
j=0
import itertools

for i in range(cv_num):
    for a,b,c in itertools.product(weights_range, repeat=model_num):
        #get combination of weights, sum to 100%
        sum_w = np.array([a,b,c]).sum()
        wts = np.array([a,b,c]) / sum_w
        
        final_proba = np.zeros((len(X_val), ))
        #get oof combination for weights
        final_proba+=proba_cat_li[i] * wts[0]
        final_proba+=proba_xgb_li[i] * wts[1]
        final_proba+=proba_lgb_li[i] * wts[2]

        #get error and put into output table
        output_wts_li[i][j,model_num] = log_loss(y_li[i], final_proba[i])

        #record the associated weights
        output_wts[i][j,0:model_num] = wts

        j+=1

In [36]:
f = np.ones((10, 205108))

In [37]:
f[0]+=y_val * 100

In [38]:
f[0]+=y_val * 100

In [39]:
f[0]

array([201., 201.,   1., ..., 201.,   1., 201.])

In [44]:
import itertools
for a,b,c in itertools.product(weights_range, repeat=3):
    #get combination of weights, sum to 100%
    sum_w = np.array([a,b,c]).sum()
    wts = np.array([a,b,c]) / sum_w
    print(wts)

[0.33333333 0.33333333 0.33333333]
[0.01923077 0.01923077 0.96153846]
[0.00980392 0.00980392 0.98039216]
[0.00657895 0.00657895 0.98684211]
[0.0049505  0.0049505  0.99009901]
[0.00396825 0.00396825 0.99206349]
[0.00331126 0.00331126 0.99337748]
[0.00284091 0.00284091 0.99431818]
[0.00248756 0.00248756 0.99502488]
[0.00221239 0.00221239 0.99557522]
[0.00199203 0.00199203 0.99601594]
[0.00181159 0.00181159 0.99637681]
[0.00166113 0.00166113 0.99667774]
[0.00153374 0.00153374 0.99693252]
[0.0014245 0.0014245 0.997151 ]
[0.00132979 0.00132979 0.99734043]
[0.00124688 0.00124688 0.99750623]
[0.00117371 0.00117371 0.99765258]
[0.00110865 0.00110865 0.99778271]
[0.00105042 0.00105042 0.99789916]
[0.000999 0.000999 0.998002]
[0.01923077 0.96153846 0.01923077]
[0.00990099 0.4950495  0.4950495 ]
[0.00662252 0.33112583 0.66225166]
[0.00497512 0.24875622 0.74626866]
[0.00398406 0.19920319 0.79681275]
[0.00332226 0.16611296 0.83056478]
[0.002849   0.14245014 0.85470085]
[0.00249377 0.12468828 0.8728

[0.06896552 0.27586207 0.65517241]
[0.06671114 0.26684456 0.6664443 ]
[0.1814882  0.81669691 0.00181488]
[0.16666667 0.75       0.08333333]
[0.15384615 0.69230769 0.15384615]
[0.14285714 0.64285714 0.21428571]
[0.13333333 0.6        0.26666667]
[0.125  0.5625 0.3125]
[0.11764706 0.52941176 0.35294118]
[0.11111111 0.5        0.38888889]
[0.10526316 0.47368421 0.42105263]
[0.1  0.45 0.45]
[0.0952381  0.42857143 0.47619048]
[0.09090909 0.40909091 0.5       ]
[0.08695652 0.39130435 0.52173913]
[0.08333333 0.375      0.54166667]
[0.08 0.36 0.56]
[0.07692308 0.34615385 0.57692308]
[0.07407407 0.33333333 0.59259259]
[0.07142857 0.32142857 0.60714286]
[0.06896552 0.31034483 0.62068966]
[0.06666667 0.3        0.63333333]
[0.06455778 0.29051001 0.64493221]
[0.16638935 0.83194676 0.00166389]
[0.15384615 0.76923077 0.07692308]
[0.14285714 0.71428571 0.14285714]
[0.13333333 0.66666667 0.2       ]
[0.125 0.625 0.25 ]
[0.11764706 0.58823529 0.29411765]
[0.11111111 0.55555556 0.33333333]
[0.10526316 0

[0.14285714 0.25       0.60714286]
[0.13793103 0.24137931 0.62068966]
[0.13333333 0.23333333 0.63333333]
[0.12911556 0.22595223 0.64493221]
[0.3327787  0.6655574  0.00166389]
[0.30769231 0.61538462 0.07692308]
[0.28571429 0.57142857 0.14285714]
[0.26666667 0.53333333 0.2       ]
[0.25 0.5  0.25]
[0.23529412 0.47058824 0.29411765]
[0.22222222 0.44444444 0.33333333]
[0.21052632 0.42105263 0.36842105]
[0.2 0.4 0.4]
[0.19047619 0.38095238 0.42857143]
[0.18181818 0.36363636 0.45454545]
[0.17391304 0.34782609 0.47826087]
[0.16666667 0.33333333 0.5       ]
[0.16 0.32 0.52]
[0.15384615 0.30769231 0.53846154]
[0.14814815 0.2962963  0.55555556]
[0.14285714 0.28571429 0.57142857]
[0.13793103 0.27586207 0.5862069 ]
[0.13333333 0.26666667 0.6       ]
[0.12903226 0.25806452 0.61290323]
[0.12507817 0.25015635 0.62476548]
[0.30721966 0.69124424 0.0015361 ]
[0.28571429 0.64285714 0.07142857]
[0.26666667 0.6        0.13333333]
[0.25   0.5625 0.1875]
[0.23529412 0.52941176 0.23529412]
[0.22222222 0.5    

[0.22222222 0.48148148 0.2962963 ]
[0.21428571 0.46428571 0.32142857]
[0.20689655 0.44827586 0.34482759]
[0.2        0.43333333 0.36666667]
[0.19354839 0.41935484 0.38709677]
[0.1875  0.40625 0.40625]
[0.18181818 0.39393939 0.42424242]
[0.17647059 0.38235294 0.44117647]
[0.17142857 0.37142857 0.45714286]
[0.16666667 0.36111111 0.47222222]
[0.16216216 0.35135135 0.48648649]
[0.15789474 0.34210526 0.5       ]
[0.15392509 0.33350436 0.51257055]
[0.2997003 0.6993007 0.000999 ]
[0.28571429 0.66666667 0.04761905]
[0.27272727 0.63636364 0.09090909]
[0.26086957 0.60869565 0.13043478]
[0.25       0.58333333 0.16666667]
[0.24 0.56 0.2 ]
[0.23076923 0.53846154 0.23076923]
[0.22222222 0.51851852 0.25925926]
[0.21428571 0.5        0.28571429]
[0.20689655 0.48275862 0.31034483]
[0.2        0.46666667 0.33333333]
[0.19354839 0.4516129  0.35483871]
[0.1875 0.4375 0.375 ]
[0.18181818 0.42424242 0.39393939]
[0.17647059 0.41176471 0.41176471]
[0.17142857 0.4        0.42857143]
[0.16666667 0.38888889 0.44

[0.29607698 0.70318283 0.00074019]
[0.28571429 0.67857143 0.03571429]
[0.27586207 0.65517241 0.06896552]
[0.26666667 0.63333333 0.1       ]
[0.25806452 0.61290323 0.12903226]
[0.25    0.59375 0.15625]
[0.24242424 0.57575758 0.18181818]
[0.23529412 0.55882353 0.20588235]
[0.22857143 0.54285714 0.22857143]
[0.22222222 0.52777778 0.25      ]
[0.21621622 0.51351351 0.27027027]
[0.21052632 0.5        0.28947368]
[0.20512821 0.48717949 0.30769231]
[0.2   0.475 0.325]
[0.19512195 0.46341463 0.34146341]
[0.19047619 0.45238095 0.35714286]
[0.18604651 0.44186047 0.37209302]
[0.18181818 0.43181818 0.38636364]
[0.17777778 0.42222222 0.4       ]
[0.17391304 0.41304348 0.41304348]
[0.17028523 0.40442742 0.42528736]
[0.28571429 0.71357143 0.00071429]
[0.27605245 0.68944099 0.03450656]
[0.26684456 0.6664443  0.06671114]
[0.25823112 0.64493221 0.09683667]
[0.25015635 0.62476548 0.12507817]
[0.24257126 0.60582171 0.15160703]
[0.23543261 0.58799294 0.17657446]
[0.22870212 0.57118353 0.20011435]
[0.222345

[0.42307692 0.11538462 0.46153846]
[0.40740741 0.11111111 0.48148148]
[0.39285714 0.10714286 0.5       ]
[0.37931034 0.10344828 0.51724138]
[0.36666667 0.1        0.53333333]
[0.35483871 0.09677419 0.5483871 ]
[0.34375 0.09375 0.5625 ]
[0.33333333 0.09090909 0.57575758]
[0.32371984 0.08828723 0.58799294]
[0.73235686 0.26631158 0.00133156]
[0.6875 0.25   0.0625]
[0.64705882 0.23529412 0.11764706]
[0.61111111 0.22222222 0.16666667]
[0.57894737 0.21052632 0.21052632]
[0.55 0.2  0.25]
[0.52380952 0.19047619 0.28571429]
[0.5        0.18181818 0.31818182]
[0.47826087 0.17391304 0.34782609]
[0.45833333 0.16666667 0.375     ]
[0.44 0.16 0.4 ]
[0.42307692 0.15384615 0.42307692]
[0.40740741 0.14814815 0.44444444]
[0.39285714 0.14285714 0.46428571]
[0.37931034 0.13793103 0.48275862]
[0.36666667 0.13333333 0.5       ]
[0.35483871 0.12903226 0.51612903]
[0.34375 0.125   0.53125]
[0.33333333 0.12121212 0.54545455]
[0.32352941 0.11764706 0.55882353]
[0.31446541 0.11435106 0.57118353]
[0.6866417  0.31

[0.27906977 0.27906977 0.44186047]
[0.2728513  0.2728513  0.45429741]
[0.47961631 0.51958433 0.00079936]
[0.46153846 0.5        0.03846154]
[0.44444444 0.48148148 0.07407407]
[0.42857143 0.46428571 0.10714286]
[0.4137931  0.44827586 0.13793103]
[0.4        0.43333333 0.16666667]
[0.38709677 0.41935484 0.19354839]
[0.375   0.40625 0.21875]
[0.36363636 0.39393939 0.24242424]
[0.35294118 0.38235294 0.26470588]
[0.34285714 0.37142857 0.28571429]
[0.33333333 0.36111111 0.30555556]
[0.32432432 0.35135135 0.32432432]
[0.31578947 0.34210526 0.34210526]
[0.30769231 0.33333333 0.35897436]
[0.3   0.325 0.375]
[0.29268293 0.31707317 0.3902439 ]
[0.28571429 0.30952381 0.4047619 ]
[0.27906977 0.30232558 0.41860465]
[0.27272727 0.29545455 0.43181818]
[0.26678524 0.28901734 0.44419742]
[0.4611837  0.53804766 0.00076864]
[0.44444444 0.51851852 0.03703704]
[0.42857143 0.5        0.07142857]
[0.4137931  0.48275862 0.10344828]
[0.4        0.46666667 0.13333333]
[0.38709677 0.4516129  0.16129032]
[0.375  0

[0.28571429 0.32653061 0.3877551 ]
[0.28011204 0.32012805 0.3997599 ]
[0.45132173 0.54803353 0.00064475]
[0.4375  0.53125 0.03125]
[0.42424242 0.51515152 0.06060606]
[0.41176471 0.5        0.08823529]
[0.4        0.48571429 0.11428571]
[0.38888889 0.47222222 0.13888889]
[0.37837838 0.45945946 0.16216216]
[0.36842105 0.44736842 0.18421053]
[0.35897436 0.43589744 0.20512821]
[0.35  0.425 0.225]
[0.34146341 0.41463415 0.24390244]
[0.33333333 0.4047619  0.26190476]
[0.3255814  0.39534884 0.27906977]
[0.31818182 0.38636364 0.29545455]
[0.31111111 0.37777778 0.31111111]
[0.30434783 0.36956522 0.32608696]
[0.29787234 0.36170213 0.34042553]
[0.29166667 0.35416667 0.35416667]
[0.28571429 0.34693878 0.36734694]
[0.28 0.34 0.38]
[0.2746175 0.3334641 0.3919184]
[0.43722673 0.56214866 0.00062461]
[0.42424242 0.54545455 0.03030303]
[0.41176471 0.52941176 0.05882353]
[0.4        0.51428571 0.08571429]
[0.38888889 0.5        0.11111111]
[0.37837838 0.48648649 0.13513514]
[0.36842105 0.47368421 0.15789

[0.35555556 0.37777778 0.26666667]
[0.34782609 0.36956522 0.2826087 ]
[0.34042553 0.36170213 0.29787234]
[0.33333333 0.35416667 0.3125    ]
[0.32653061 0.34693878 0.32653061]
[0.32 0.34 0.34]
[0.31372549 0.33333333 0.35294118]
[0.30769231 0.32692308 0.36538462]
[0.30200076 0.3208758  0.37712344]
[0.47031158 0.52910053 0.00058789]
[0.45714286 0.51428571 0.02857143]
[0.44444444 0.5        0.05555556]
[0.43243243 0.48648649 0.08108108]
[0.42105263 0.47368421 0.10526316]
[0.41025641 0.46153846 0.12820513]
[0.4  0.45 0.15]
[0.3902439  0.43902439 0.17073171]
[0.38095238 0.42857143 0.19047619]
[0.37209302 0.41860465 0.20930233]
[0.36363636 0.40909091 0.22727273]
[0.35555556 0.4        0.24444444]
[0.34782609 0.39130435 0.26086957]
[0.34042553 0.38297872 0.27659574]
[0.33333333 0.375      0.29166667]
[0.32653061 0.36734694 0.30612245]
[0.32 0.36 0.32]
[0.31372549 0.35294118 0.33333333]
[0.30769231 0.34615385 0.34615385]
[0.30188679 0.33962264 0.35849057]
[0.29640608 0.33345684 0.37013709]
[0.4

[0.79166667 0.08333333 0.125     ]
[0.76 0.08 0.16]
[0.73076923 0.07692308 0.19230769]
[0.7037037  0.07407407 0.22222222]
[0.67857143 0.07142857 0.25      ]
[0.65517241 0.06896552 0.27586207]
[0.63333333 0.06666667 0.3       ]
[0.61290323 0.06451613 0.32258065]
[0.59375 0.0625  0.34375]
[0.57575758 0.06060606 0.36363636]
[0.55882353 0.05882353 0.38235294]
[0.54285714 0.05714286 0.4       ]
[0.52777778 0.05555556 0.41666667]
[0.51351351 0.05405405 0.43243243]
[0.5        0.05263158 0.44736842]
[0.48717949 0.05128205 0.46153846]
[0.475 0.05  0.475]
[0.4636408  0.04880429 0.4875549 ]
[0.86285195 0.13623978 0.00090827]
[0.82608696 0.13043478 0.04347826]
[0.79166667 0.125      0.08333333]
[0.76 0.12 0.12]
[0.73076923 0.11538462 0.15384615]
[0.7037037  0.11111111 0.18518519]
[0.67857143 0.10714286 0.21428571]
[0.65517241 0.10344828 0.24137931]
[0.63333333 0.1        0.26666667]
[0.61290323 0.09677419 0.29032258]
[0.59375 0.09375 0.3125 ]
[0.57575758 0.09090909 0.33333333]
[0.55882353 0.08823